export default class ApplicationsPage {
    iconApplication = 'i[data-id="Applications'
    linkNewApp = '.new > a:nth-child(1) > span:nth-child(2)'
    linkApp = '.application > span:nth-child(2)'
    inputAppName = 'input[name=name]'
    buttonSave = '.dip-view-body > .btn-panel > .xl-primary'
    linkAppPermissionDisabled = 'li.new.dropdown-submenu.disabled'
    linkViewPermissions = '.viewPermissions'
    linkNewDepPkg = '.deploymentPackage > span:nth-child(2)'
    linkNew = '.new > a:nth-child(1)'
    linkNewCmd = '.cmd > a:nth-child(1) > span:nth-child(2)'
    selectCommand = '.command > span:nth-child(2)'
    textAreaAppCmd = ':nth-child(1) > .xl-react-category-content > :nth-child(1) > .xl-react-components > .xl-react-components-input > .xl-react-widget-string-input-container > .xl-react-component-input-wrapper > textarea'
    selectAppTree = '.infinite-tree-selected > .infinite-tree-node > .infinite-tree-toggler'
    linkNewFile = '.file > a:nth-child(1) > span:nth-child(2)'
    menuFile = '[data-path="new->file->file"] > .file > .menu-item-label'
    inputFileUpload = 'input[name=ajax_upload_file_input]'
    buttonBrowse = 'button[type=button]'
    buttonSaveFile = 'button[type=button]'
    linkRescanArtifact = 'ul.dropdown-menu:nth-child(1) > li:nth-child(9) > a:nth-child(1) > span:nth-child(2)'
    buttonSchedule = '.schedule'
    selectSchedule = '.schedule > a:nth-child(1)'
    linkAppEditPermissions = '.editPermissions > span:nth-child(2)'
    buttonSaveAndClose = '.save-and-close'
}